### ISSUE TITLE
Usage samples

### ISSUE THREAD

**Issue by ricardomaraschini** [rprobaina/lpfs#1]
Can we have some usage examples ?

**Comment by rprobaina** [comment]
Hi @ricardomaraschini,

Thanks for your suggestion! 

I've added some code snippets both in the [README.md](https://github.com/rprobaina/lpfs/blob/main/README.md) and in [/lpfs/examples](https://github.com/rprobaina/lpfs/tree/main/examples) directory.
Let me know what you think!

Best regards,
Ricardo

**Comment by ricardomaraschini** [comment]
Good stuff @rprobaina ! Is there any plan to process the files under `/proc/<pid>` as well ?

**Comment by rprobaina** [comment]
> Good stuff @rprobaina ! Is there any plan to process the files under `/proc/<pid>` as well ?

Sure thing, @ricardomaraschini! Actually, I've been working on it and finished a usable version today. Take a look at `GetPerProcessStat()`, it gets data from: `/proc/<pid>/stat` and returns a slice of per-process stats.

I've added the following **very simple** examples on [/lpfs/examples](https://github.com/rprobaina/lpfs/tree/main/examples) dir.
* [Find Top Memory (RSS) consumers in the system](https://github.com/rprobaina/lpfs/blob/main/examples/per_proc_top_RSS.go)
* [Show all processes' state](https://github.com/rprobaina/lpfs/blob/main/examples/per_proc_state.go)

**Comment by ricardomaraschini** [comment]
Excellent @rprobaina, thank you for acting upon my request, I really appreciate it.
